### ISSUE TITLE
Missing dependency 'import gd'

### ISSUE THREAD

**Issue by MartinThoma** [CodeforKarlsruhe/trinkwasser-scraper#1]
I don't have that module. Where is it from?

**Comment by MartinThoma** [comment]
Ok, I found the solution for Ubuntu:

```
$ sudo apt-get install python-gd
```

I suggest adding a section `## Requirements` to the README where this is listed (as well as `pip install -r requirements.txt`)

**Comment by torfsen** [comment]
Good idea, fixed. Thanks for your input!
